from __future__ import annotations

import json
import os
import urllib.error
import urllib.request


def propose_resolution(conflict_file, classification: dict) -> dict | None:
    """Return one optional LLM candidate, or None when no approved model endpoint is configured.

    The adapter deliberately treats the model as an untrusted proposal generator: its response is
    returned to the normal AST scoring and isolated validation stages and is never auto-applied.
    """

    endpoint = os.environ.get("MERGEPILOT_LLM_URL")
    if not endpoint:
        return None

    model = os.environ.get("MERGEPILOT_LLM_MODEL", "local-merge-model")
    prompt = {
        "task": "Resolve a Git merge conflict. Return JSON with only `content` and `explanation`.",
        "classification": classification["classification"],
        "filePath": conflict_file.path,
        "base": conflict_file.base_content,
        "target": conflict_file.target_content,
        "source": conflict_file.source_content,
        "constraints": [
            "Preserve valid syntax.",
            "Do not invent dependencies.",
            "Explain the semantic trade-off concisely.",
        ],
    }
    request_payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a conservative source-code merge assistant. Output valid JSON only."},
            {"role": "user", "content": json.dumps(prompt)},
        ],
        "response_format": {"type": "json_object"},
        "temperature": 0.1,
    }
    headers = {"Content-Type": "application/json"}
    api_key = os.environ.get("MERGEPILOT_LLM_API_KEY")
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        request = urllib.request.Request(
            endpoint,
            data=json.dumps(request_payload).encode("utf-8"),
            headers=headers,
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=20) as response:
            payload = json.loads(response.read().decode("utf-8"))
        raw_content = payload.get("choices", [{}])[0].get("message", {}).get("content", "")
        proposal = json.loads(raw_content) if isinstance(raw_content, str) else raw_content
        content = proposal.get("content", "")
        explanation = proposal.get("explanation", "LLM-assisted proposal generated by the configured local/API model.")
        if not isinstance(content, str) or not content.strip():
            return None
        return {
            "strategy": "llm-assisted",
            "label": "LLM-assisted conservative merge",
            "content": content,
            "explanation": explanation,
            "semanticImpact": "An optional model proposal that remains untrusted until it passes the same AST scoring and isolated validation gates.",
        }
    except (urllib.error.URLError, ValueError, KeyError, IndexError, json.JSONDecodeError):
        return None
